### ISSUE TITLE
Countdown to NDoCH

### ISSUE THREAD

**Issue by NathanRSmith** [HackMichiana/HackMichiana.github.io#3]
Countdown timer for NDoCH event.
6pm friday June 5th

**Comment by NathanRSmith** [comment]
Branch https://github.com/HackMichiana/HackMichiana.github.io/tree/ndoch-countdown

**Comment by NathanRSmith** [comment]
It's live @charlesguse

**Comment by charlesguse** [comment]
Woot cool!
